version: 2

sphinx:
  configuration: docs/conf.py

build:
  image: latest

python:
  version: 3.8
  install:
    - requirements: git+https://github.com/parafoxia/analytix@task/rewrite
    - requirements: requirements/rtd.txt
