name: CI (Checks)

on:
  [push, pull_request]

jobs:
  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install nox

      - name: Run checks
        run: |
          python -m nox -k "not tests"
